<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Induction acknowledgement</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #111; }
        h1 { font-size: 18px; margin-bottom: 4px; }
        .muted { color: #444; font-size: 10px; margin-bottom: 16px; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; vertical-align: top; }
        th { background: #f0f0f0; }
        .sig { max-height: 80px; }
        .meta { margin-top: 20px; font-size: 10px; color: #333; }
    </style>
</head>
<body>
    <h1>Induction acknowledgement record</h1>
    <p class="muted">{{ $enrollment->version->policy->name }} — version {{ $enrollment->version->version_label }}</p>
    <p><strong>Employee:</strong> {{ $enrollment->user->name }} ({{ $enrollment->user->email }})</p>
    <p><strong>Completed at:</strong> {{ $enrollment->completed_at?->timezone(config('app.timezone'))->format('Y-m-d H:i:s T') }}</p>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Section</th>
                <th>Date / time</th>
                <th>Policy version</th>
                <th>IP / device</th>
                <th>Signature</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($completions as $c)
                <tr>
                    <td>{{ $c->section->sort_order }}</td>
                    <td>
                        {{ $c->section->title }}
                        <div style="font-size:9px;color:#444;margin-top:4px;">Acknowledged as: {{ $c->employee_name_snapshot }}</div>
                    </td>
                    <td>{{ $c->completed_at?->timezone(config('app.timezone'))->format('Y-m-d H:i:s') }}</td>
                    <td>{{ $c->policy_version_label_snapshot }}</td>
                    <td>
                        {{ $c->ip_address ?? '—' }}
                        @if ($c->user_agent)
                            <div style="font-size:8px;color:#555;margin-top:3px;word-break:break-all;">{{ \Illuminate\Support\Str::limit($c->user_agent, 140) }}</div>
                        @endif
                    </td>
                    <td>
                        @if ($c->signature_path && $c->signature_disk && \Illuminate\Support\Facades\Storage::disk($c->signature_disk)->exists($c->signature_path))
                            @php
                                $data = base64_encode(\Illuminate\Support\Facades\Storage::disk($c->signature_disk)->get($c->signature_path));
                            @endphp
                            <img class="sig" src="data:image/png;base64,{{ $data }}" alt="" width="160">
                        @else
                            —
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="meta">
        <p>This document was generated by {{ config('app.name') }}.</p>
    </div>
</body>
</html>
